// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "todoerdemo-20190106135506-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://todoerdemo-20190106135506-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:63870266-bd94-4e50-b48e-4281ab5a3615",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aaS1u5LN6",
    "aws_user_pools_web_client_id": "7e8ip5jv90lv3gsbhlmc1lkuqd"
};


export default awsmobile;
